# Generated by Django 5.2.6 on 2025-10-20 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='shared_todolists', to=settings.AUTH_USER_MODEL),
        ),
    ]
