# Generated by Django 5.2.6 on 2025-10-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem_description_todolist_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='members',
        ),
    ]
